"""
Foundation primitives for Agentic Assistants core.

This package contains reusable, framework-agnostic building blocks for:
- validated base models and mixins
- typed DTO boundaries
- repository and service contracts
- registry and plugin extension points
- serializer backends
- state machine orchestration
- observability facades
- shared typing protocols
"""

from agentic_assistants.core.foundation.base_models import (
    AgenticAuditEntity,
    AgenticBaseModel,
    AgenticEntity,
    AgenticSlugEntity,
    AuditMixin,
    Envelope,
    EntityStatus,
    ErrorDetail,
    ErrorResponse,
    HealthCheck,
    MetadataMixin,
    PaginatedResponse,
    SlugMixin,
    SoftDeleteMixin,
    StatusMixin,
    TagsMixin,
    TimestampMixin,
    UUIDMixin,
    VersionedMixin,
)
from agentic_assistants.core.foundation.clients import (
    HTTPDatasetClient,
    MLFlowClient,
    MinioObjectStoreClient,
    PrefectClient,
)
from agentic_assistants.core.foundation.dto import BaseDTO, CreateDTO, DTOConfig, ReadDTO, UpdateDTO
from agentic_assistants.core.foundation.observability import BackendType, ObservabilityManager
from agentic_assistants.core.foundation.registry import (
    AdapterRegistry,
    AutoRegistry,
    DataSourceTypeRegistry,
    NodeTypeRegistry,
    PatternRegistry,
    ProviderRegistry,
    SerializerRegistry,
)
from agentic_assistants.core.foundation.repository import (
    AbstractRepository,
    FilterSpec,
    InMemoryRepository,
    PaginationSpec,
    SortSpec,
    SQLAlchemyRepository,
)
from agentic_assistants.core.foundation.serialization import (
    JsonSerializer,
    MsgspecSerializer,
    PydanticSerializer,
    Serializer,
    get_serializer,
    register_serializer,
)
from agentic_assistants.core.foundation.service import AuditedService, BaseService, DomainEvent
from agentic_assistants.core.foundation.state_machine import (
    END,
    START,
    Checkpointer,
    CompiledGraph,
    ConditionalEdge,
    InMemoryCheckpointer,
    StateMachine,
    StateNode,
)
from agentic_assistants.core.foundation.types import (
    AdapterRunMetadata,
    ChatHistory,
    ChatMessage,
    CollectionName,
    DataCatalogProtocol,
    Embedding,
    EvalResult,
    ExecutionResult,
    ExecutionStatus,
    HookManagerProtocol,
    JSON,
    Metadata,
    ModelName,
    NodeInputs,
    NodeOutputs,
    ProviderName,
    RunID,
    SkillPayload,
    ToolResult,
    ToolSpec,
    TrainingState,
)
from agentic_assistants.core.foundation.utils import (
    append_step,
    deep_merge_state,
    ensure_bytes,
    ensure_required_keys,
    ensure_within_range,
    merge_metadata,
    project_state,
    safe_json_dumps,
    safe_json_loads,
    select_metadata,
)

__all__ = [
    "AgenticBaseModel",
    "TimestampMixin",
    "UUIDMixin",
    "SlugMixin",
    "SoftDeleteMixin",
    "AuditMixin",
    "TagsMixin",
    "MetadataMixin",
    "AgenticEntity",
    "AgenticAuditEntity",
    "AgenticSlugEntity",
    "VersionedMixin",
    "StatusMixin",
    "EntityStatus",
    "ErrorDetail",
    "PaginatedResponse",
    "Envelope",
    "ErrorResponse",
    "HealthCheck",
    "DTOConfig",
    "BaseDTO",
    "CreateDTO",
    "ReadDTO",
    "UpdateDTO",
    "MLFlowClient",
    "PrefectClient",
    "HTTPDatasetClient",
    "MinioObjectStoreClient",
    "AbstractRepository",
    "FilterSpec",
    "SortSpec",
    "PaginationSpec",
    "InMemoryRepository",
    "SQLAlchemyRepository",
    "BaseService",
    "AuditedService",
    "DomainEvent",
    "AutoRegistry",
    "ProviderRegistry",
    "AdapterRegistry",
    "PatternRegistry",
    "DataSourceTypeRegistry",
    "SerializerRegistry",
    "NodeTypeRegistry",
    "Serializer",
    "JsonSerializer",
    "PydanticSerializer",
    "MsgspecSerializer",
    "get_serializer",
    "register_serializer",
    "START",
    "END",
    "StateNode",
    "ConditionalEdge",
    "Checkpointer",
    "InMemoryCheckpointer",
    "StateMachine",
    "CompiledGraph",
    "BackendType",
    "ObservabilityManager",
    "JSON",
    "Embedding",
    "ChatMessage",
    "ChatHistory",
    "ToolResult",
    "ToolSpec",
    "Metadata",
    "NodeInputs",
    "NodeOutputs",
    "ModelName",
    "ProviderName",
    "CollectionName",
    "RunID",
    "TrainingState",
    "EvalResult",
    "SkillPayload",
    "DataCatalogProtocol",
    "HookManagerProtocol",
    "ExecutionStatus",
    "ExecutionResult",
    "AdapterRunMetadata",
    "merge_metadata",
    "select_metadata",
    "safe_json_dumps",
    "safe_json_loads",
    "ensure_bytes",
    "deep_merge_state",
    "append_step",
    "project_state",
    "ensure_required_keys",
    "ensure_within_range",
]

